### ISSUE TITLE
profile.getEncryptionKeypair() is returning 401 with Error: Wrong signature

### ISSUE THREAD

**Issue by ryejoon** [HandCash/handcash-connect-sdk-js#12]
In my localhost environment `profile.getEncryptionKeypair()` is returning 401.

`GET https://cloud.handcash.io/v1/connect/profile/encryptionKeypair`

```
core.js:6479 ERROR Error: Wrong signature
    at handleApiError (handcash_connect_service.js:152)
    at ZoneDelegate.invoke (zone.js:372)
```

My app has `Encrypt` permission. I tried with new app, and after clearing browser cache, the result is the same. (also tried Chrome, Safari. and Node.js)
Other APIs are working fine, but only `getEncryptionKeypair` is not working.

**Comment by rseibane** [comment]
Hi @ryejoon, thanks for reporting. We are working on this issue. We'll keep you posted 👍

**Comment by ryejoon** [comment]
The api is working fine with same configuration in node.js environment. It only fails in my browser. Looks like my browser library (such as `crypto.js`) is generating wrong signature for the same input:  https://github.com/HandCash/handcash-connect-sdk-js/blob/master/src/api/http_request_factory.js#L51-L57

**Comment by ryejoon** [comment]
> The api is working fine with same configuration in node.js environment.
I'm correcting myself here. Today it's failing in my node.js environment as well.

**Comment by joelocktime** [comment]
+1 I'm getting this error too.

**Comment by joelocktime** [comment]
If a GET request has a body, it's ignored, probably why we're seeing this signature error. https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/send

I see you are putting the encryptionKeyPair in the body for this API request.

https://github.com/HandCash/handcash-connect-sdk-js/blob/b2911a670bdfceaab6a4f3d61e812137fa58b615/src/api/http_request_factory.js#L116

This might be a big change on your end, are there any temporary workarounds?

**Comment by rseibane** [comment]
Just published a new version that should fix the issues with some HTTP endpoints over GET. 
Can you check if that solves your issues? https://www.npmjs.com/package/@handcash/handcash-connect/v/0.3.0

**Comment by joelocktime** [comment]
Works in my browser, thank you for the fix!

<img width="581" alt="Screen Shot 2022-01-07 at 12 11 29 PM" src="https://user-images.githubusercontent.com/93632327/148601465-6011b2e4-0578-4977-88be-2ce4aae3e9aa.png">

**Comment by ryejoon** [comment]
Works in my browser too. Thanks a lot!

**Comment by rseibane** [comment]
Thank you guys for reporting and for being patient! ❤️
