### ISSUE TITLE
Content-Type header is missing

### ISSUE THREAD

**Issue by alexb5dh** [HandCash/handcash-connect-sdk-js#22]
All requests done by `HandcashConnect` don't pass `Content-Type` header. While HC servers expects JSON and probably don't use this flag, it's easy to add and can be useful to request loggers, proxies, etc.

Since client is only sending JSON, fix can be as simple as adding `Content-Type: application/json` (or `Content-type: application/json; charset=utf-8`) header in request factory method.

**Comment by rseibane** [comment]
Makes sense to me. This has low impact but also low effort so we'll try to get it done this week.

**Comment by rafa-js** [comment]
This should be covered from version `0.6.13`. Check [this](https://github.com/HandCash/handcash-connect-sdk-js/pull/56) out.

Thanks for reporting!
